name: "Terraform version check"

on:
  push:
    branches:
      - main
    paths-ignore:
        - 'README.md'
        - '.gitignore'
  pull_request:
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - '.github/*'
    - '.pre-commit-config.yaml'

jobs:
  # Terraformのワーキングディレクトリ一覧を取得
  collectInputs:
    name: "Collect workflow inputs"
    runs-on: ubuntu-latest
    outputs:
        directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@v1.3.0

  # チェック
  checkTFMinVersion:
      name: " Min TF Check"
      needs: collectInputs
      runs-on: ubuntu-latest
      strategy:
        matrix:
          dir: ${{ fromJson(needs.collectInputs.outputs.directories) }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform min/max versions
          id: minMax
          uses: clowdhaus/terraform-min-max@v1.0.3
          with:
            directory: ${{ matrix.dir }}

        - name: Terraform ${{ steps.minMax.outputs.minVersion }}
          if: ${{ matrix.dir !=  '.' }}
          uses: clowdhaus/terraform-composite-actions/pre-commit@v1.3.0
          with:
            args: 'terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.dir }}/*'
            terraform-version: ${{ steps.minMax.outputs.minVersion }}

        - name: Terraform ${{ steps.minMax.outputs.minVersion }}
          if: ${{ matrix.dir ==  '.' }}
          uses: clowdhaus/terraform-composite-actions/pre-commit@v1.3.0
          with:
            args: 'terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)'
            terraform-version: ${{ steps.minMax.outputs.minVersion }}

  checkTFMaxVersion:
    name: Max TF Check
    runs-on: ubuntu-latest
    needs: collectInputs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.0.3

      - name: Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.3.0
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
